spring.application.name=aja
logging.level.org.springframework.security=DEBUG



# https://www.geeksforgeeks.org/advance-java/how-to-enable-https-in-spring-boot-application/
# Activando TLS para usar HTTPS y cifrar las comunicaciones cliente/servidor
server.port=8443
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=144741
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat


