spring.application.name=aja
logging.level.org.springframework.security=DEBUG



# https://www.geeksforgeeks.org/advance-java/how-to-enable-https-in-spring-boot-application/
# Activando TLS para usar HTTPS y cifrar las comunicaciones cliente/servidor
server.address=0.0.0.0
server.port=8443
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=144741
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=springboot




keytool -genkeypair \
      -alias springboot \
      -keyalg RSA \
      -keysize 2048 \
      -keystore keystore.p12 \
      -storetype PKCS12 \
      -storepass 144741 \
      -keypass 144741 \
      -validity 365 \
      -dname "CN=ajateam.dev, OU=Dev, O=Aja Team, L=Barcelona, ST=Spain, C=ES" \
      -ext "SAN=dns:*.mel0n.dev,dns:localhost,ip:127.0.0.1"